theme: jekyll-theme-cayman
title: NordSec 2022
description: The 27th Nordic Conference on Secure IT Systems
conference_location: Reykjavik University, Iceland
conference_date: 30 November 2022 - 02 December 2022
top_navs:
  - title: "Call For Paper"
    anchor: "#call-for-papers"
  - title: "Submission"
    anchor: "#submission-guidelines"
  - title: "Schedule"
    anchor: "#preliminary-conference-schedule"
  - title: "Proceedings"
    anchor: "#proceedings"
  - title: "Registration"
    anchor: "#registration-information"
  - title: "Venue"
    anchor: "#location"
  - title: "Important dates"
    anchor: "#important-dates"
  - title: "Committees"
    anchor: "#committees"
  - title: "Contact"
    anchor: "#contact"
